
name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup maven settings
        run: |
          mkdir -p $HOME/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0">
            <servers>
              <server>
                <id>github</id>
                <username>alabienG</username>
                <password>${{ secrets.PASSWORD }}</password>
              </server>
            </servers>
          </settings>
          EOF
      - name: Build Project
        run: mvn clean install