
name: Build

on:
  workflow_call:
    secrets:
      TOKEN_CI:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup maven settings
        run: |
          mkdir -p $HOME/.m2
          cp settings.xml $HOME/.m2/ 
          sed -i "s|{{PASSWORD}}|${{secrets.TOKEN_CI}}|g" $HOME/.m2/settings.xml
          sed -i "s|{{USERNAME}}|alabienG|g" $HOME/.m2/settings.xml
          cat $HOME/.m2/settings.xml

      - name: Build Project
        run: mvn clean install
