
name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup maven settings
        run: |
          mkdir -p $HOME/.m2
          cp settings.xml $HOME/.m2/
      - name: Build Project
        run: mvn clean install
