name: lymytz_ci_template

on:
  workflow_call:
    secrets:
      REPOSITORY_TOKEN:
        required: true
      SONAR_TOKEN:
        required: false
      SONAR_HOST_URL:
        required: false
      VM_HOST:
        required: false
      VM_SSH_KEY:
        required: false
      VM_USER:
        required: false
    inputs:
      repository_username:
        type: string
        required: false
        default: ${{github.repository_owner}}
      java_version:
        type: string
        required: true
      fat_jar_name:
        type: string
        required: false
        default: 'app'
      compile_opt:
        type: string
        required: false
        default: ''
      project_key:
        type: string
        required: false
      project_name:
        type: string
        required: false
jobs:
  Compile:
    name: Compilation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{inputs.java_version}}
          distribution: temurin
      - name: Pre-Compile # Préparation du maven-settings (download & update credential)
        run: |
          echo " récupération du template settings.xml"
          curl -sSL --fail -o settings_template.xml https://raw.githubusercontent.com/Lymytz/ci_actions/main/settings.xml
      - name: Apply credential
        run: |
          sed "s|__USERNAME__|${{inputs.repository_username}}|g" settings_template.xml > settings.xml
          sed -i "s|__PASSWORD__|${{secrets.REPOSITORY_TOKEN}}|g" settings.xml
      - name: Move settings.xml
        run: |
          echo "HOME is $HOME"
          mkdir -p "$HOME/.m2"
          mv --force settings.xml "$HOME/.m2/"
        shell: bash
      - name: Compilation
        run: |
          echo "Compilation avec la distribution"
          java -version
          mvn ${{inputs.compile_opt}} --settings "$HOME/.m2/settings.xml" compile
      - name: Upload compile class
        uses: actions/upload-artifact@v4
        with:
          name: compiled-classes
          path: '**/target/classes'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: "$HOME/.m2/repository"
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-
  UnitTest:
    needs: Compile
    name: Test Unitaire
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{inputs.java_version}}
          cache: 'maven'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: "$HOME/.m2/repository"
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-
      - name: Pre-Test
        run: |
          echo " récupération du template settings.xml"
          curl -sSL --fail -o settings_template.xml https://raw.githubusercontent.com/Lymytz/ci_actions/main/settings.xml
          sed "s|__USERNAME__|${{inputs.repository_username}}|g" settings_template.xml > settings.xml
          sed -i "s|__PASSWORD__|${{secrets.REPOSITORY_TOKEN}}|g" settings.xml
          mkdir -p "$HOME/.m2"
          mv --force settings.xml "$HOME/.m2/"
        shell: bash
      - name: Download compiled classes
        uses: actions/download-artifact@v4
        with:
          name: compiled-classes
          path: .
      - name: Run test with coverage
        run: |
          mvn verify -Dmaven.test.skip=false -Dmaven.main.skip=true
      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: report-coverage
          path:
            aggregate-report/target/
  IntegrationTest:
    needs: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{inputs.java_version}}
          cache: 'maven'
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{inputs.java_version}}
          cache: 'maven'
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: "$HOME/.m2/repository"
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-
      - name: Pre-Test
        run: |
          echo " récupération du template settings.xml"
          curl -sSL --fail -o settings_template.xml https://raw.githubusercontent.com/Lymytz/ci_actions/main/settings.xml
          sed "s|__USERNAME__|${{inputs.repository_username}}|g" settings_template.xml > settings.xml
          sed -i "s|__PASSWORD__|${{secrets.REPOSITORY_TOKEN}}|g" settings.xml
          mkdir -p "$HOME/.m2"
          mv --force settings.xml "$HOME/.m2/"
        shell: bash
      - name: Dowload compiled classes
        uses: actions/download-artifact@v4
        with:
          name: compiled-classes
          path: .
      - name: Run tests
        run: |
          mvn verify -Pintegration -Dmaven.compile.skip=true
      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: report-coverage
          path: aggregate-report/target/


  QualityCheck:  # Lancer l'analyse sonar, envoyer les rapports TU à sonar
    needs:
      - IntegrationTest
      - UnitTest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download reports
        uses: actions/download-artifact@v4
        with:
          name: report-integration-coverage
          path: .
      - name: Sonar analysis
        env:
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
          SONAR_HOST_URL: ${{secrets.SONAR_HOST_URL}}
          PROJECT_KEY: ${{inputs.project_key}}
        run: |
          mvn sonar:sonar -Dsonar.coverage.jacoco.xmlReportPaths=aggregate-report/target/site/jacoco-aggregate/jacoco.xml"
          -Dsonar.host.url=$SONAR_HOST_URL
          -Dsonar.projectKey=$PROJECT_KEY
          -Dsonar.projectName=$PROJECT_NAME
          -Dmaven.test.skip=true
  BuildImage:
    needs: QualityCheck
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build docker image"
  Deploy:
    needs: BuildImage
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy application"
